import { CfnOutput, Duration, RemovalPolicy, Stack, type StackProps } from "aws-cdk-lib";
import { InstanceClass, InstanceSize, InstanceType, Port, SecurityGroup, SubnetType, type SecurityGroup as SG, type Vpc } from "aws-cdk-lib/aws-ec2";
import {
  Credentials,
  DatabaseInstance,
  DatabaseInstanceEngine,
  PostgresEngineVersion,
  StorageType,
} from "aws-cdk-lib/aws-rds";
import type { ISecret } from "aws-cdk-lib/aws-secretsmanager";
import type { Construct } from "constructs";

export interface NettleDatabaseStackProps extends StackProps {
  vpc: Vpc;
  connectorSecurityGroup: SG;
  /** Production gets deletion protection and longer backups. */
  production?: boolean;
  /**
   * Automated-backup retention, in days. Defaults to 7 — not 14 or 35 — because
   * RDS itself rejects anything past a lower cap for accounts still under AWS
   * Free Tier eligibility ("Resource handler returned message: The specified
   * backup retention period exceeds the maximum available to free tier
   * customers"), which is a real error this stack hit on its first deploy.
   * Raise this once the account is past Free Tier eligibility, if a longer
   * retention window is wanted.
   */
  backupRetentionDays?: number;
  /**
   * Set to deploy a second, independent database (e.g. "staging") from this
   * same stack definition. Left undefined, the generated credentials
   * secret's name is unchanged from before this parameter existed — see
   * api-stack.ts's identical stageName prop for why that matters. Only
   * affects the secret name; databaseName ("nettle") is intentionally the
   * same in every environment; it's scoped by which physical RDS instance
   * it lives in, not by name.
   */
  stageName?: string;
}

/**
 * The durable store for all Nettle application state.
 *
 * Why this exists: the application previously kept users, sessions, projects,
 * scans, scan history, billing anchors, notification preferences and events in
 * a SQLite file inside the App Runner container. App Runner replaces that
 * container on every deployment and when it scales, so all of it was
 * destroyed on each deploy. App Runner has no persistent-filesystem
 * integration — CfnService exposes no volume or mount property of any kind —
 * so an EFS-backed SQLite file is not an option; the data has to live in a
 * managed database outside the container.
 *
 * Sizing: db.t4g.micro. The workload is small relational reads and writes, and
 * a single small instance is the smallest thing that satisfies durability.
 * Aurora Serverless v2 would cost more at this scale because of its 0.5 ACU
 * floor. Scale up, or to Multi-AZ, when real load justifies it.
 */
export class NettleDatabaseStack extends Stack {
  public readonly instance: DatabaseInstance;
  public readonly secret: ISecret;
  public readonly port: number;

  constructor(scope: Construct, id: string, props: NettleDatabaseStackProps) {
    super(scope, id, props);

    const production = props.production ?? true;
    const backupRetentionDays = props.backupRetentionDays ?? 7;

    const dbSecurityGroup = new SecurityGroup(this, "DatabaseSecurityGroup", {
      vpc: props.vpc,
      description: "Nettle PostgreSQL - reachable only from the App Runner VPC connector",
      allowAllOutbound: false,
    });

    // The only ingress rule on the database: PostgreSQL, from the App Runner
    // connector's security group. Not a CIDR, and emphatically not
    // 0.0.0.0/0 — referencing the SG means the rule stays correct even if
    // subnet ranges change.
    dbSecurityGroup.addIngressRule(
      props.connectorSecurityGroup,
      Port.tcp(5432),
      "PostgreSQL from the Nettle API only"
    );

    this.instance = new DatabaseInstance(this, "Postgres", {
      engine: DatabaseInstanceEngine.postgres({ version: PostgresEngineVersion.VER_16_3 }),
      instanceType: InstanceType.of(InstanceClass.BURSTABLE4_GRAVITON, InstanceSize.MICRO),
      vpc: props.vpc,
      // Isolated subnets: the database has no route to the internet, in
      // either direction.
      vpcSubnets: { subnetType: SubnetType.PRIVATE_ISOLATED },
      securityGroups: [dbSecurityGroup],
      // Never reachable from outside the VPC.
      publiclyAccessible: false,

      databaseName: "nettle",
      // Credentials are generated by Secrets Manager and never appear in this
      // source, in CloudFormation parameters, or in any environment file. The
      // password is not knowable from the repository.
      credentials: Credentials.fromGeneratedSecret("nettle_app", {
        secretName: `nettle/database/credentials${props.stageName ? `-${props.stageName}` : ""}`,
      }),

      allocatedStorage: 20,
      maxAllocatedStorage: 100, // storage autoscaling, so a full disk is not an outage
      storageType: StorageType.GP3,
      storageEncrypted: true, // encryption at rest, AWS-managed key

      backupRetention: Duration.days(production ? backupRetentionDays : 1),
      deleteAutomatedBackups: !production,
      deletionProtection: production,
      removalPolicy: production ? RemovalPolicy.RETAIN : RemovalPolicy.DESTROY,

      // A snapshot on delete means an accidental stack teardown is recoverable.
      copyTagsToSnapshot: true,
      enablePerformanceInsights: false, // not available on t4g.micro
      autoMinorVersionUpgrade: true,
      multiAz: false, // single-AZ at this size; revisit with real load
    });

    this.secret = this.instance.secret!;
    this.port = 5432;

    new CfnOutput(this, "DatabaseEndpoint", { value: this.instance.dbInstanceEndpointAddress });
    new CfnOutput(this, "DatabaseSecretArn", {
      value: this.secret.secretArn,
      description: "Secrets Manager secret holding the generated database credentials",
    });
  }
}
