-- Baseline schema.
--
-- Deliberately dialect-neutral: it runs unchanged on SQLite and PostgreSQL.
-- That is possible because every primary key is a TEXT UUID generated by the
-- application (crypto.randomUUID) and every timestamp is an ISO-8601 string
-- generated in JS, so there is no AUTOINCREMENT, no rowid dependence, no
-- CURRENT_TIMESTAMP and no engine-specific date handling anywhere.
--
-- Booleans in notification_preferences stay INTEGER 0/1 rather than becoming
-- PostgreSQL BOOLEAN, so the value the application reads back is identical on
-- both engines.

CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  plan TEXT NOT NULL DEFAULT 'free',
  stripe_customer_id TEXT,
  subscription_status TEXT NOT NULL DEFAULT 'none',
  created_at TEXT NOT NULL,
  billing_anchor TEXT
);

CREATE TABLE IF NOT EXISTS sessions (
  token_hash TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  created_at TEXT NOT NULL,
  expires_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);

CREATE TABLE IF NOT EXISTS password_resets (
  token_hash TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  expires_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_password_resets_user ON password_resets(user_id);

CREATE TABLE IF NOT EXISTS projects (
  id TEXT PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  name TEXT NOT NULL,
  api_key TEXT NOT NULL UNIQUE,
  url TEXT,
  description TEXT,
  environment TEXT NOT NULL DEFAULT 'production',
  archived_at TEXT,
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_projects_user ON projects(user_id);

CREATE TABLE IF NOT EXISTS events (
  id TEXT PRIMARY KEY,
  project_id TEXT NOT NULL REFERENCES projects(id),
  occurred_at TEXT NOT NULL,
  ip TEXT,
  method TEXT,
  path TEXT,
  status_code INTEGER,
  user_agent TEXT
);
CREATE INDEX IF NOT EXISTS idx_events_project_time ON events(project_id, occurred_at);

CREATE TABLE IF NOT EXISTS alerts (
  id TEXT PRIMARY KEY,
  project_id TEXT NOT NULL REFERENCES projects(id),
  occurred_at TEXT NOT NULL,
  severity TEXT NOT NULL,
  rule TEXT NOT NULL,
  message TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'new'
);
CREATE INDEX IF NOT EXISTS idx_alerts_project_time ON alerts(project_id, occurred_at);

CREATE TABLE IF NOT EXISTS scans (
  id TEXT PRIMARY KEY,
  project_id TEXT NOT NULL REFERENCES projects(id),
  scanned_at TEXT NOT NULL,
  score INTEGER NOT NULL,
  critical_count INTEGER NOT NULL,
  caution_count INTEGER NOT NULL,
  clear_count INTEGER NOT NULL,
  report_json TEXT NOT NULL,
  scanner_version TEXT,
  status TEXT NOT NULL DEFAULT 'COMPLETED'
);
CREATE INDEX IF NOT EXISTS idx_scans_project_time ON scans(project_id, scanned_at);

CREATE TABLE IF NOT EXISTS finding_statuses (
  id TEXT PRIMARY KEY,
  project_id TEXT NOT NULL REFERENCES projects(id),
  finding_hash TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'open',
  notes TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_finding_statuses_unique
  ON finding_statuses(project_id, finding_hash);

CREATE TABLE IF NOT EXISTS notification_preferences (
  user_id TEXT PRIMARY KEY REFERENCES users(id),
  email_critical_alerts INTEGER NOT NULL DEFAULT 1,
  email_scan_complete INTEGER NOT NULL DEFAULT 1,
  email_weekly_summary INTEGER NOT NULL DEFAULT 0,
  slack_webhook_url TEXT
);

-- Billable scans are recorded here rather than counted off `scans`: a scan run
-- without a project API key never lands in `scans` at all, so counting stored
-- reports would let a subscriber take unlimited full-price scans simply by
-- omitting the key.
CREATE TABLE IF NOT EXISTS scan_usage (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  project_id TEXT,
  source TEXT NOT NULL,
  occurred_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_scan_usage_user_time ON scan_usage(user_id, occurred_at);
